# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#   'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# -------------------------------------
# Site Settings
# -------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title  }}, {{ site.email  }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable  }}.

name: antego
title: GSOC Devlog
description: Progress of Series REST-API Cache project

gh_name: antego
gh_commits: https://github.com/52North/series-rest-api-cache/commits/?author=antego
gh_prs: https://github.com/52North/series-rest-api-cache/pulls?utf8=%E2%9C%93&q=is:pr+author:antego
gh_issues: https://github.com/52North/series-rest-api-cache/issues?utf8=%E2%9C%93&q=is:issue+author:antego
gh_project: https://github.com/52North/series-rest-api-cache/

# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encodig: utf-8
highlighter: rouge
